"""
PMS Backend Launcher — Production entry point for PyInstaller sidecar.

Responsibilities:
  1. Initialize DATA_DIR (%LOCALAPPDATA%/PMS-Data) on first run
  2. Copy template database, license keys, and .env if missing
  3. Find a free port (prefer 8000, fallback to OS-assigned)
  4. Print PMS_PORT:<port> to stdout for Tauri to capture
  5. Start uvicorn on the chosen port
  6. Handle clean shutdown on SIGTERM / process kill
"""

import sys
import os
import socket
import shutil
import signal

def find_free_port(preferred: int = 8000) -> int:
    """Try the preferred port first; if busy, let the OS assign one."""
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        sock.bind(('127.0.0.1', preferred))
        sock.close()
        return preferred
    except OSError:
        sock.close()
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.bind(('127.0.0.1', 0))
        port = sock.getsockname()[1]
        sock.close()
        return port


def initialize_data_dir():
    """On first run, copy template files from the bundle to DATA_DIR."""
    from core.config import DATA_DIR, BUNDLE_DIR, IS_FROZEN

    if not IS_FROZEN:
        return  # Dev mode — nothing to do

    # Template database (clean, no real data — generated by prepare_build.py)
    template_db = os.path.join(BUNDLE_DIR, 'data_template', 'clean_pharma_db.sqlite')
    target_db = os.path.join(DATA_DIR, 'pharma_db.sqlite')
    legacy_db = os.path.join(os.path.dirname(sys.executable), 'pharma_db.sqlite')
    if not os.path.isfile(target_db):
        source_db = legacy_db if os.path.isfile(legacy_db) else template_db
        if os.path.isfile(source_db):
            shutil.copy2(source_db, target_db)
            print(f"[PMS] Initialized database at {target_db} from {source_db}", flush=True)

    # License validation public key
    template_keys = os.path.join(BUNDLE_DIR, 'data_template', 'keys')
    target_keys = os.path.join(DATA_DIR, 'utils', 'keys')
    if os.path.isdir(template_keys) and not os.path.isdir(target_keys):
        os.makedirs(target_keys, exist_ok=True)
        for f in os.listdir(template_keys):
            src = os.path.join(template_keys, f)
            dst = os.path.join(target_keys, f)
            if os.path.isfile(src) and not os.path.isfile(dst):
                shutil.copy2(src, dst)

    # Licenses directory — create empty; NEVER pre-seed with bundled .lic files.
    # Licenses are device-bound. Copying them would give every new machine the
    # developer's personal license, which is a security and data-isolation bug.
    target_lic = os.path.join(DATA_DIR, 'licenses')
    os.makedirs(target_lic, exist_ok=True)
    legacy_license = os.path.join(os.path.dirname(sys.executable), 'licenses', 'active.lic')
    target_license = os.path.join(target_lic, 'active.lic')
    if os.path.isfile(legacy_license) and not os.path.isfile(target_license):
        shutil.copy2(legacy_license, target_license)
        print(f"[PMS] Migrated legacy license to {target_license}", flush=True)

    # Default .env — write it with an ABSOLUTE database path so the engine
    # always resolves to the persistent DATA_DIR file, never to a relative
    # path depending on the current working directory.
    target_env = os.path.join(DATA_DIR, '.env')
    if not os.path.isfile(target_env):
        db_url = target_db.replace(chr(92), "/")
        env_content = f"DATABASE_URL=sqlite:///{db_url}\nEXPIRY_ALERT_DAYS=30\n"
        with open(target_env, 'w') as f:
            f.write(env_content)
        print(f"[PMS] Initialized config at {target_env}", flush=True)


def main():
    # Set the working directory to the bundle root (important for relative paths)
    if getattr(sys, 'frozen', False):
        os.chdir(os.path.dirname(sys.executable))

    # Initialize first-run data
    initialize_data_dir()

    # All mutable files (database, uploads, logs, backups) must resolve under
    # the per-user data directory. Program Files is read-only after install.
    if getattr(sys, 'frozen', False):
        from core.config import DATA_DIR, settings
        os.chdir(DATA_DIR)
        print(f"[PMS] Data directory: {DATA_DIR}", flush=True)
        print(f"[PMS] Database path: {os.path.join(DATA_DIR, 'pharma_db.sqlite')}", flush=True)
        print(f"[PMS] Database URL: {settings.DATABASE_URL}", flush=True)
        print(f"[PMS] License directory: {os.path.join(DATA_DIR, 'licenses')}", flush=True)

    # Find a free port
    port = find_free_port(8000)

    # ── CRITICAL: Print the port for Tauri to capture ──────────────────────
    print(f"PMS_PORT:{port}", flush=True)

    # Graceful shutdown handler
    def shutdown_handler(signum, frame):
        print("[PMS] Shutting down gracefully...", flush=True)
        sys.exit(0)

    signal.signal(signal.SIGTERM, shutdown_handler)
    signal.signal(signal.SIGINT, shutdown_handler)

    # Start uvicorn
    import uvicorn
    from main import app  # Direct import so PyInstaller bundles it
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=port,
        log_level="info",
        reload=False,
    )


if __name__ == "__main__":
    main()
