"""Add performance indexes

Revision ID: 0297cbbf4d8c
Revises: 8cdd21e09901
Create Date: 2026-09-20 12:05:20.396948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0297cbbf4d8c'
down_revision: Union[str, Sequence[str], None] = '8cdd21e09901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index('IX_Purchases_PurchaseDate', ['PurchaseDate'], unique=False)
        batch_op.create_index('IX_Purchases_SupplierId', ['SupplierId'], unique=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index('IX_SaleItems_BatchId', ['BatchId'], unique=False)
        batch_op.create_index('IX_SaleItems_SalesId', ['SalesId'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index('IX_Sales_CustomerId', ['CustomerId'], unique=False)
        batch_op.create_index('IX_Sales_Status', ['Status'], unique=False)
        batch_op.create_index('IX_Sales_TransactionDate', ['TransactionDate'], unique=False)
        batch_op.create_index('IX_Sales_UserId', ['UserId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('IX_Sales_UserId')
        batch_op.drop_index('IX_Sales_TransactionDate')
        batch_op.drop_index('IX_Sales_Status')
        batch_op.drop_index('IX_Sales_CustomerId')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index('IX_SaleItems_SalesId')
        batch_op.drop_index('IX_SaleItems_BatchId')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index('IX_Purchases_SupplierId')
        batch_op.drop_index('IX_Purchases_PurchaseDate')

    # ### end Alembic commands ###
