"""add_stock_adjustments

Revision ID: 1c362700ec99
Revises: f98f3ee48e8c
Create Date: 2026-08-04 15:30:03.834095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c362700ec99'
down_revision: Union[str, Sequence[str], None] = 'f98f3ee48e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_adjustments',
    sa.Column('AdjustmentId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BatchId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('AdjustmentType', sa.String(length=20), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Reason', sa.Text(), nullable=False),
    sa.Column('AdjustmentDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("AdjustmentType IN ('Increase', 'Decrease')", name='check_adjustment_type'),
    sa.CheckConstraint('Quantity > 0', name='check_adjustment_qty_positive'),
    sa.ForeignKeyConstraint(['BatchId'], ['stock_batches.BatchId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('AdjustmentId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_adjustments')
    # ### end Alembic commands ###
