"""purchase_financial_fields

Revision ID: 1f071c169ed1
Revises: 5155cdbe3596
Create Date: 2026-08-04 11:28:24.005456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f071c169ed1'
down_revision: Union[str, Sequence[str], None] = '5155cdbe3596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FreeQty', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Discount', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('TaxPercentage', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('LineTotal', sa.Numeric(precision=18, scale=2), nullable=False))

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SupplierInvNo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('PaymentStatus', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('PaymentMethod', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('Notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('SubTotal', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('TotalDiscount', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('TotalTax', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('GrandTotal', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('PaidAmount', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('RemainingBalance', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.drop_column('TotalAmount')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TotalAmount', sa.NUMERIC(precision=18, scale=2), nullable=False))
        batch_op.drop_column('RemainingBalance')
        batch_op.drop_column('PaidAmount')
        batch_op.drop_column('GrandTotal')
        batch_op.drop_column('TotalTax')
        batch_op.drop_column('TotalDiscount')
        batch_op.drop_column('SubTotal')
        batch_op.drop_column('Notes')
        batch_op.drop_column('PaymentMethod')
        batch_op.drop_column('PaymentStatus')
        batch_op.drop_column('SupplierInvNo')

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_column('LineTotal')
        batch_op.drop_column('TaxPercentage')
        batch_op.drop_column('Discount')
        batch_op.drop_column('FreeQty')

    # ### end Alembic commands ###
