"""Add BackupSettings table

Revision ID: 23365c0d1b57
Revises: f008eab21242
Create Date: 2026-08-06 16:38:24.374149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23365c0d1b57'
down_revision: Union[str, Sequence[str], None] = 'f008eab21242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_settings',
    sa.Column('SettingsId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IsAutoBackupEnabled', sa.Boolean(), nullable=True),
    sa.Column('BackupFrequency', sa.String(length=50), nullable=True),
    sa.Column('BackupTime', sa.String(length=10), nullable=True),
    sa.Column('BackupLocation', sa.String(length=500), nullable=True),
    sa.Column('RetentionCount', sa.Integer(), nullable=True),
    sa.Column('BackupOnStartup', sa.Boolean(), nullable=True),
    sa.Column('CompressBackup', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('SettingsId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_settings')
    # ### end Alembic commands ###
