"""add_printer_settings

Revision ID: 24528071675c
Revises: b2b2d34c3d01
Create Date: 2026-08-07 22:27:42.878555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24528071675c'
down_revision: Union[str, Sequence[str], None] = 'b2b2d34c3d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer_settings',
    sa.Column('SettingsId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PrinterType', sa.String(length=50), nullable=False),
    sa.Column('PaperSize', sa.String(length=50), nullable=False),
    sa.Column('SelectedPrinterName', sa.String(length=255), nullable=True),
    sa.Column('ConnectionPort', sa.String(length=50), nullable=False),
    sa.Column('CustomRawByteSequence', sa.Text(), nullable=True),
    sa.Column('ShowLogo', sa.Boolean(), nullable=False),
    sa.Column('ShowPharmacyName', sa.Boolean(), nullable=False),
    sa.Column('ShowAddress', sa.Boolean(), nullable=False),
    sa.Column('ReceiptFooterMessage', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SettingsId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printer_settings')
    # ### end Alembic commands ###
