"""add composite index for sales

Revision ID: 2581b6ba3257
Revises: 0297cbbf4d8c
Create Date: 2026-09-20 14:02:43.936979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2581b6ba3257'
down_revision: Union[str, Sequence[str], None] = '0297cbbf4d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index('IX_Sales_Status_TransactionDate', ['Status', 'TransactionDate'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('IX_Sales_Status_TransactionDate')

    # ### end Alembic commands ###
