"""update_sale_fields

Revision ID: 29f45c9bbdfb
Revises: 1c362700ec99
Create Date: 2026-08-04 23:32:14.218334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f45c9bbdfb'
down_revision: Union[str, Sequence[str], None] = '1c362700ec99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Discount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('Tax', sa.Numeric(precision=18, scale=2), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TaxAmount', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('PaidAmount', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('Status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('PrescriptionRef', sa.String(length=100), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Email', sa.String(length=100), nullable=True))
        batch_op.drop_column('TaxNumber')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TaxNumber', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('Email')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('PrescriptionRef')
        batch_op.drop_column('Status')
        batch_op.drop_column('PaidAmount')
        batch_op.drop_column('TaxAmount')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_column('Tax')
        batch_op.drop_column('Discount')

    # ### end Alembic commands ###
