"""add_pharmacy_profile

Revision ID: 2a6e71bc6cf9
Revises: 64ed627f5027
Create Date: 2026-08-06 23:23:29.166105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6e71bc6cf9'
down_revision: Union[str, Sequence[str], None] = '64ed627f5027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_profile',
    sa.Column('ProfileId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PharmacyName', sa.String(length=255), nullable=False),
    sa.Column('OwnerName', sa.String(length=255), nullable=True),
    sa.Column('RegistrationNumber', sa.String(length=100), nullable=True),
    sa.Column('DrugLicenseNumber', sa.String(length=100), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=50), nullable=True),
    sa.Column('EmailAddress', sa.String(length=255), nullable=True),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('State', sa.String(length=100), nullable=True),
    sa.Column('Country', sa.String(length=100), nullable=True),
    sa.Column('PostalCode', sa.String(length=20), nullable=True),
    sa.Column('Website', sa.String(length=255), nullable=True),
    sa.Column('LogoPath', sa.String(length=500), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('ProfileId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pharmacy_profile')
    # ### end Alembic commands ###
