"""remove opening stock

Revision ID: 4e5e634e5725
Revises: a3f8c9d2e1b4
Create Date: 2026-09-24 12:46:22.167815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5e634e5725'
down_revision: Union[str, Sequence[str], None] = 'a3f8c9d2e1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opening_stock_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('UQ_os_entries_ImportHash'))
        batch_op.drop_index(batch_op.f('UQ_os_entries_ReferenceNo'))

    op.drop_table('opening_stock_entries')
    with op.batch_alter_table('opening_stock_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_opening_stock_items_EntryId'))

    op.drop_table('opening_stock_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_stock_items',
    sa.Column('ItemId', sa.INTEGER(), nullable=False),
    sa.Column('EntryId', sa.INTEGER(), nullable=False),
    sa.Column('BatchId', sa.INTEGER(), nullable=False),
    sa.Column('MedicineId', sa.INTEGER(), nullable=False),
    sa.Column('BatchCode', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Quantity', sa.INTEGER(), nullable=False),
    sa.Column('CostPrice', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('SellingPrice', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('ExpiryDate', sa.DATE(), nullable=False),
    sa.Column('ManufacturingDate', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['BatchId'], ['stock_batches.BatchId'], ),
    sa.ForeignKeyConstraint(['EntryId'], ['opening_stock_entries.EntryId'], ),
    sa.ForeignKeyConstraint(['MedicineId'], ['medicines.MedicineId'], ),
    sa.PrimaryKeyConstraint('ItemId')
    )
    with op.batch_alter_table('opening_stock_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_opening_stock_items_EntryId'), ['EntryId'], unique=False)

    op.create_table('opening_stock_entries',
    sa.Column('EntryId', sa.INTEGER(), nullable=False),
    sa.Column('ReferenceNo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ImportHash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('Notes', sa.TEXT(), nullable=True),
    sa.Column('EntryDate', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('CreatedBy', sa.INTEGER(), nullable=False),
    sa.Column('TotalItems', sa.INTEGER(), nullable=True),
    sa.Column('TotalValue', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('ImportFile', sa.VARCHAR(length=255), nullable=True),
    sa.Column('Status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'"), nullable=True),
    sa.Column('VoidedAt', sa.DATETIME(), nullable=True),
    sa.Column('VoidedBy', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.UserId'], ),
    sa.ForeignKeyConstraint(['VoidedBy'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('EntryId')
    )
    with op.batch_alter_table('opening_stock_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('UQ_os_entries_ReferenceNo'), ['ReferenceNo'], unique=1)
        batch_op.create_index(batch_op.f('UQ_os_entries_ImportHash'), ['ImportHash'], unique=1)

    # ### end Alembic commands ###
