"""Add Medicine metadata fields

Revision ID: 5155cdbe3596
Revises: fb0e1a8b6d35
Create Date: 2026-08-04 01:32:14.669553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5155cdbe3596'
down_revision: Union[str, Sequence[str], None] = 'fb0e1a8b6d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Unit', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('Barcode', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('DefaultCostPrice', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('DefaultSellingPrice', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.create_unique_constraint('uq_medicines_barcode', ['Barcode'])
        batch_op.create_foreign_key('fk_medicines_companies', 'companies', ['CompanyId'], ['CompanyId'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_medicines_companies', type_='foreignkey')
        batch_op.drop_constraint('uq_medicines_barcode', type_='unique')
        batch_op.drop_column('DefaultSellingPrice')
        batch_op.drop_column('DefaultCostPrice')
        batch_op.drop_column('Barcode')
        batch_op.drop_column('Unit')
        batch_op.drop_column('CompanyId')

    # ### end Alembic commands ###
