"""Initial schema single user

Revision ID: 5f27e56da61e
Revises: 
Create Date: 2026-08-03 00:03:39.627996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f27e56da61e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('CategoryId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CategoryName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('CategoryId'),
    sa.UniqueConstraint('CategoryName')
    )
    op.create_table('customers',
    sa.Column('CustomerId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('LoyaltyPoints', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('CustomerId')
    )
    op.create_table('suppliers',
    sa.Column('SupplierId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Phone', sa.String(length=20), nullable=False),
    sa.Column('TaxNumber', sa.String(length=50), nullable=True),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SupplierId')
    )
    op.create_table('users',
    sa.Column('UserId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('PasswordHash', sa.String(length=256), nullable=False),
    sa.Column('Salt', sa.String(length=128), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('audit_logs',
    sa.Column('LogId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Action', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.Text(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('LogId')
    )
    op.create_table('medicines',
    sa.Column('MedicineId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BrandName', sa.String(length=100), nullable=False),
    sa.Column('GenericName', sa.String(length=100), nullable=False),
    sa.Column('CategoryId', sa.Integer(), nullable=False),
    sa.Column('RackNumber', sa.String(length=20), nullable=True),
    sa.Column('ReorderLevel', sa.Integer(), nullable=False),
    sa.Column('RequiresPrescription', sa.Boolean(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['CategoryId'], ['categories.CategoryId'], ),
    sa.PrimaryKeyConstraint('MedicineId')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_index('IX_Medicines_BrandName', ['BrandName'], unique=False)

    op.create_table('purchases',
    sa.Column('PurchaseId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SupplierId', sa.Integer(), nullable=False),
    sa.Column('InvoiceNumber', sa.String(length=50), nullable=False),
    sa.Column('TotalAmount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('PurchaseDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SupplierId'], ['suppliers.SupplierId'], ),
    sa.PrimaryKeyConstraint('PurchaseId')
    )
    op.create_table('sales',
    sa.Column('SalesId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerId', sa.Integer(), nullable=True),
    sa.Column('InvoiceNumber', sa.String(length=50), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('SubTotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('DiscountAmount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('GrandTotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('PaymentMethod', sa.String(length=20), nullable=False),
    sa.Column('TransactionDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['CustomerId'], ['customers.CustomerId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('SalesId'),
    sa.UniqueConstraint('InvoiceNumber')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index('IX_Sales_InvoiceNumber', ['InvoiceNumber'], unique=False)

    op.create_table('purchase_items',
    sa.Column('PurchaseItemId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PurchaseId', sa.Integer(), nullable=False),
    sa.Column('MedicineId', sa.Integer(), nullable=False),
    sa.Column('BatchCode', sa.String(length=50), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('CostPrice', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('SellingPrice', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ExpiryDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['MedicineId'], ['medicines.MedicineId'], ),
    sa.ForeignKeyConstraint(['PurchaseId'], ['purchases.PurchaseId'], ),
    sa.PrimaryKeyConstraint('PurchaseItemId')
    )
    op.create_table('stock_batches',
    sa.Column('BatchId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MedicineId', sa.Integer(), nullable=False),
    sa.Column('BatchCode', sa.String(length=50), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('CostPrice', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('SellingPrice', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ExpiryDate', sa.Date(), nullable=False),
    sa.Column('ReceivedDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('Quantity >= 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['MedicineId'], ['medicines.MedicineId'], ),
    sa.PrimaryKeyConstraint('BatchId')
    )
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.create_index('IX_StockBatches_Medicine_Expiry', ['MedicineId', 'ExpiryDate', 'Quantity'], unique=False)

    op.create_table('sale_items',
    sa.Column('SalesItemId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SalesId', sa.Integer(), nullable=False),
    sa.Column('BatchId', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('TotalPrice', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('Quantity > 0', name='check_sale_quantity_positive'),
    sa.ForeignKeyConstraint(['BatchId'], ['stock_batches.BatchId'], ),
    sa.ForeignKeyConstraint(['SalesId'], ['sales.SalesId'], ),
    sa.PrimaryKeyConstraint('SalesItemId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_items')
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.drop_index('IX_StockBatches_Medicine_Expiry')

    op.drop_table('stock_batches')
    op.drop_table('purchase_items')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('IX_Sales_InvoiceNumber')

    op.drop_table('sales')
    op.drop_table('purchases')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index('IX_Medicines_BrandName')

    op.drop_table('medicines')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('customers')
    op.drop_table('categories')
    # ### end Alembic commands ###
