"""add_autoverify_to_backupsettings

Revision ID: 64ed627f5027
Revises: 23365c0d1b57
Create Date: 2026-08-06 22:04:21.428568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ed627f5027'
down_revision: Union[str, Sequence[str], None] = '23365c0d1b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AutoVerify', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_settings', schema=None) as batch_op:
        batch_op.drop_column('AutoVerify')

    # ### end Alembic commands ###
