"""add receipt logo path

Revision ID: 7a4b58fbb42b
Revises: e1d04af346ba
Create Date: 2026-08-29 16:13:37.327172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4b58fbb42b'
down_revision: Union[str, Sequence[str], None] = 'e1d04af346ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ReceiptLogoPath', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy_profile', schema=None) as batch_op:
        batch_op.drop_column('ReceiptLogoPath')

    # ### end Alembic commands ###
