"""centralize_receipt_settings

Revision ID: 8cdd21e09901
Revises: b3c4d5e6f7a8b9c0d1e2f3
Create Date: 2026-09-18 09:42:52.853739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdd21e09901'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PharmacyName', sa.String(length=255), nullable=False, server_default="My Pharmacy"))
        batch_op.add_column(sa.Column('PharmacyAddress', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('PharmacyPhone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('DrugLicenseNumber', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('NtnStrn', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('Website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ReceiptLogoPath', sa.String(length=500), nullable=True))

    # Copy data from pharmacy_profile to printer_settings
    conn = op.get_bind()
    # Read the first pharmacy profile
    res = conn.execute(sa.text("SELECT PharmacyName, Address, PhoneNumber, DrugLicenseNumber, NtnStrn, Website, ReceiptLogoPath, ReceiptFooter1 FROM pharmacy_profile LIMIT 1"))
    profile = res.fetchone()
    
    if profile:
        params = {
            "name": profile[0] or "My Pharmacy",
            "address": profile[1],
            "phone": profile[2],
            "license": profile[3],
            "ntn": profile[4],
            "website": profile[5],
            "logo": profile[6],
            "footer": profile[7] or "Thank you for your visit!"
        }
        
        has_settings = conn.execute(sa.text("SELECT 1 FROM printer_settings LIMIT 1")).fetchone() is not None
        
        if has_settings:
            update_stmt = sa.text("""
                UPDATE printer_settings 
                SET PharmacyName = :name,
                    PharmacyAddress = :address,
                    PharmacyPhone = :phone,
                    DrugLicenseNumber = :license,
                    NtnStrn = :ntn,
                    Website = :website,
                    ReceiptLogoPath = :logo,
                    ReceiptFooterMessage = :footer
            """)
            conn.execute(update_stmt, params)
        else:
            insert_stmt = sa.text("""
                INSERT INTO printer_settings (
                    PharmacyName, PharmacyAddress, PharmacyPhone, DrugLicenseNumber,
                    NtnStrn, Website, ReceiptLogoPath, ReceiptFooterMessage
                ) VALUES (
                    :name, :address, :phone, :license, :ntn, :website, :logo, :footer
                )
            """)
            conn.execute(insert_stmt, params)

    op.drop_table('pharmacy_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer_settings', schema=None) as batch_op:
        batch_op.drop_column('ReceiptLogoPath')
        batch_op.drop_column('Website')
        batch_op.drop_column('NtnStrn')
        batch_op.drop_column('DrugLicenseNumber')
        batch_op.drop_column('PharmacyPhone')
        batch_op.drop_column('PharmacyAddress')
        batch_op.drop_column('PharmacyName')

    op.create_table('pharmacy_profile',
    sa.Column('ProfileId', sa.INTEGER(), nullable=False),
    sa.Column('PharmacyName', sa.VARCHAR(length=255), nullable=False),
    sa.Column('OwnerName', sa.VARCHAR(length=255), nullable=True),
    sa.Column('RegistrationNumber', sa.VARCHAR(length=100), nullable=True),
    sa.Column('DrugLicenseNumber', sa.VARCHAR(length=100), nullable=True),
    sa.Column('PhoneNumber', sa.VARCHAR(length=50), nullable=True),
    sa.Column('EmailAddress', sa.VARCHAR(length=255), nullable=True),
    sa.Column('Address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('City', sa.VARCHAR(length=100), nullable=True),
    sa.Column('State', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('PostalCode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('Website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('LogoPath', sa.VARCHAR(length=500), nullable=True),
    sa.Column('UpdatedAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('PharmacySlogan', sa.VARCHAR(length=255), nullable=True),
    sa.Column('NtnStrn', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ReceiptLogoPath', sa.VARCHAR(length=500), nullable=True),
    sa.Column('ReceiptFooter1', sa.VARCHAR(length=255), server_default=sa.text("'Thank you for your visit!'"), nullable=True),
    sa.Column('ReceiptFooter2', sa.VARCHAR(length=255), server_default=sa.text("'Software provided by Eagle Nest Creations'"), nullable=True),
    sa.PrimaryKeyConstraint('ProfileId')
    )
    # ### end Alembic commands ###
