"""Add Company model

Revision ID: 91656536201a
Revises: 6cd55dda1cfd
Create Date: 2026-08-04 00:57:00.882828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91656536201a'
down_revision: Union[str, Sequence[str], None] = '6cd55dda1cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('CompanyId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CompanyName', sa.String(length=100), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('CompanyId'),
    sa.UniqueConstraint('CompanyName')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
