"""Add Purchase financial fields

Revision ID: 93e79d884aab
Revises: 1f071c169ed1
Create Date: 2026-08-04 11:34:04.203447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e79d884aab'
down_revision: Union[str, Sequence[str], None] = '1f071c169ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('PaymentMethod',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('PaymentMethod',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
