"""rename_supplier_email_to_taxnumber

Revision ID: b021df1b1175
Revises: fd0affdec134
Create Date: 2026-08-08 01:51:43.334449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b021df1b1175'
down_revision: Union[str, Sequence[str], None] = 'fd0affdec134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TaxNumber', sa.String(length=100), nullable=True))
        batch_op.drop_column('Email')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Email', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('TaxNumber')

    # ### end Alembic commands ###
