"""add_inventory_settings_revised

Revision ID: b2b2d34c3d01
Revises: df132f27f7ab
Create Date: 2026-08-07 21:57:39.786201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b2d34c3d01'
down_revision: Union[str, Sequence[str], None] = 'df132f27f7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_settings',
    sa.Column('SettingsId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LowStockThreshold', sa.Integer(), nullable=False),
    sa.Column('ExpiryAlertDays', sa.Integer(), nullable=False),
    sa.Column('AllowNegativeStock', sa.Boolean(), nullable=False),
    sa.Column('DefaultUnit', sa.String(length=50), nullable=False),
    sa.Column('AutoGenerateBarcode', sa.Boolean(), nullable=False),
    sa.Column('PreventSaleOfExpired', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('SettingsId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_settings')
    # ### end Alembic commands ###
