"""Add Mfg Date

Revision ID: b5b737fe569e
Revises: 93e79d884aab
Create Date: 2026-08-04 12:10:55.411522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b737fe569e'
down_revision: Union[str, Sequence[str], None] = '93e79d884aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ManufacturingDate', sa.Date(), nullable=True))

    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ManufacturingDate', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.drop_column('ManufacturingDate')

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_column('ManufacturingDate')

    # ### end Alembic commands ###
