"""Add DismissedNotification model

Revision ID: be237f406e8a
Revises: c1d2e3f4a5b6
Create Date: 2026-09-25 08:39:02.342855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be237f406e8a'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dismissed_notifications',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EntityKey', sa.String(length=150), nullable=False),
    sa.Column('DismissedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('dismissed_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dismissed_notifications_EntityKey'), ['EntityKey'], unique=True)

    with op.batch_alter_table('billing_settings', schema=None) as batch_op:
        batch_op.alter_column('DefaultDiscountRate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('(0.00)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_settings', schema=None) as batch_op:
        batch_op.alter_column('DefaultDiscountRate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('(0.00)'))

    with op.batch_alter_table('dismissed_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dismissed_notifications_EntityKey'))

    op.drop_table('dismissed_notifications')
    # ### end Alembic commands ###
