"""add_billing_settings

Revision ID: df132f27f7ab
Revises: 2a6e71bc6cf9
Create Date: 2026-08-07 19:06:49.686014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df132f27f7ab'
down_revision: Union[str, Sequence[str], None] = '2a6e71bc6cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_settings',
    sa.Column('SettingsId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Currency', sa.String(length=10), nullable=False),
    sa.Column('CurrencySymbol', sa.String(length=5), nullable=False),
    sa.Column('TaxEnabled', sa.Boolean(), nullable=False),
    sa.Column('DefaultTaxRate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('DiscountEnabled', sa.Boolean(), nullable=False),
    sa.Column('MaxDiscountPercentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('AdminDiscountThreshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('RequireAdminPinForDiscount', sa.Boolean(), nullable=False),
    sa.Column('InvoicePrefix', sa.String(length=20), nullable=False),
    sa.Column('NextInvoiceNumber', sa.Integer(), nullable=False),
    sa.Column('DefaultPaymentMethod', sa.String(length=50), nullable=False),
    sa.Column('AutoPrintReceipt', sa.Boolean(), nullable=False),
    sa.Column('ShowKeyboardShortcuts', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('SettingsId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_settings')
    # ### end Alembic commands ###
