"""Add BackupHistory table

Revision ID: df4127e34428
Revises: e5c117bb8996
Create Date: 2026-08-06 12:25:18.412101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4127e34428'
down_revision: Union[str, Sequence[str], None] = 'e5c117bb8996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_history',
    sa.Column('BackupId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BackupName', sa.String(length=255), nullable=False),
    sa.Column('BackupLocation', sa.String(length=500), nullable=False),
    sa.Column('SizeBytes', sa.Integer(), nullable=False),
    sa.Column('BackupType', sa.String(length=50), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('ChecksumSHA256', sa.String(length=64), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('BackupId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_history')
    # ### end Alembic commands ###
