"""add slogan and ntn to pharmacy profile

Revision ID: e1d04af346ba
Revises: b021df1b1175
Create Date: 2026-08-29 15:44:07.888555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d04af346ba'
down_revision: Union[str, Sequence[str], None] = 'b021df1b1175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('CategoryName',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_categories_CategoryName'), ['CategoryName'], unique=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_CompanyName'), ['CompanyName'], unique=True)

    with op.batch_alter_table('pharmacy_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PharmacySlogan', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('NtnStrn', sa.String(length=100), nullable=True))

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.alter_column('RefundMode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False,
               existing_server_default=sa.text("'Cash Refund'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.alter_column('RefundMode',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Cash Refund'"))

    with op.batch_alter_table('pharmacy_profile', schema=None) as batch_op:
        batch_op.drop_column('NtnStrn')
        batch_op.drop_column('PharmacySlogan')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_CompanyName'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_CategoryName'))
        batch_op.alter_column('CategoryName',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
