"""Add SaleReturn models

Revision ID: e5c117bb8996
Revises: 29f45c9bbdfb
Create Date: 2026-08-05 01:45:06.286387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c117bb8996'
down_revision: Union[str, Sequence[str], None] = '29f45c9bbdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_returns',
    sa.Column('ReturnId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SalesId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('ReturnInvoiceNumber', sa.String(length=50), nullable=False),
    sa.Column('TotalRefundAmount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('Reason', sa.Text(), nullable=False),
    sa.Column('ReturnDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['SalesId'], ['sales.SalesId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('ReturnId'),
    sa.UniqueConstraint('ReturnInvoiceNumber')
    )
    op.create_table('sale_return_items',
    sa.Column('ReturnItemId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ReturnId', sa.Integer(), nullable=False),
    sa.Column('BatchId', sa.Integer(), nullable=False),
    sa.Column('ReturnQuantity', sa.Integer(), nullable=False),
    sa.Column('RefundAmount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ItemCondition', sa.String(length=50), nullable=False),
    sa.CheckConstraint("ItemCondition IN ('Restockable', 'Damaged/Quarantine')", name='check_sale_return_condition'),
    sa.CheckConstraint('ReturnQuantity > 0', name='check_sale_return_qty_positive'),
    sa.ForeignKeyConstraint(['BatchId'], ['stock_batches.BatchId'], ),
    sa.ForeignKeyConstraint(['ReturnId'], ['sale_returns.ReturnId'], ),
    sa.PrimaryKeyConstraint('ReturnItemId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_return_items')
    op.drop_table('sale_returns')
    # ### end Alembic commands ###
