"""Add Purchase Returns

Revision ID: f98f3ee48e8c
Revises: b5b737fe569e
Create Date: 2026-08-04 12:30:06.572054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98f3ee48e8c'
down_revision: Union[str, Sequence[str], None] = 'b5b737fe569e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_returns',
    sa.Column('ReturnId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PurchaseId', sa.Integer(), nullable=False),
    sa.Column('SupplierId', sa.Integer(), nullable=False),
    sa.Column('ReturnInvoiceNumber', sa.String(length=50), nullable=False),
    sa.Column('ReturnDate', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('TotalRefundAmount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('Reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['PurchaseId'], ['purchases.PurchaseId'], ),
    sa.ForeignKeyConstraint(['SupplierId'], ['suppliers.SupplierId'], ),
    sa.PrimaryKeyConstraint('ReturnId'),
    sa.UniqueConstraint('ReturnInvoiceNumber')
    )
    op.create_table('purchase_return_items',
    sa.Column('ReturnItemId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ReturnId', sa.Integer(), nullable=False),
    sa.Column('MedicineId', sa.Integer(), nullable=False),
    sa.Column('BatchCode', sa.String(length=50), nullable=False),
    sa.Column('ReturnQuantity', sa.Integer(), nullable=False),
    sa.Column('RefundAmount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['MedicineId'], ['medicines.MedicineId'], ),
    sa.ForeignKeyConstraint(['ReturnId'], ['purchase_returns.ReturnId'], ),
    sa.PrimaryKeyConstraint('ReturnItemId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_return_items')
    op.drop_table('purchase_returns')
    # ### end Alembic commands ###
