"""add_system_preferences

Revision ID: fd0affdec134
Revises: 24528071675c
Create Date: 2026-08-07 22:49:49.270023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0affdec134'
down_revision: Union[str, Sequence[str], None] = '24528071675c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_preferences',
    sa.Column('SettingsId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Theme', sa.String(length=50), nullable=False),
    sa.Column('DateFormat', sa.String(length=50), nullable=False),
    sa.Column('TimeFormat', sa.String(length=50), nullable=False),
    sa.Column('NumberFormat', sa.String(length=50), nullable=False),
    sa.Column('StartupModule', sa.String(length=50), nullable=False),
    sa.Column('EnableAudioAlerts', sa.Boolean(), nullable=False),
    sa.Column('EnableToastNotifications', sa.Boolean(), nullable=False),
    sa.Column('Language', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('SettingsId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_preferences')
    # ### end Alembic commands ###
